### ISSUE TITLE
Problems with MathJax in Markdown

### ISSUE THREAD

**Issue by SpaceCafe** [elb-min-uhh/markdown-elearnjs#2]
**Describe the bug**
This tool ignores MathJax code. If you use reserved Markdown characters, like `_`, it'll be converted to an `<em>` Element. Therefore, it is not possible to use *atom-elearnjs* to create reports with formulas.

**To Reproduce**
1. Write `$x_{i}$ bla bla $x_{i}$`
2. See error in HTML: `$x<em>i$ bla bla $x</em>i$`

**Expected behavior**
Do not touch MathJax!

**Comment by westarne** [comment]
I cannot test this atm. But does 
`$x\_{i}$ bla bla $x\_{i}$` work, maybe?

Otherwise i might have to check other possibilities.

You might need to surround the area with html:

```
<div>
$x_{i}$ bla bla $x_{i}$
</div>
```

Or


```
<div markdown=0>
$x_{i}$ bla bla $x_{i}$
</div>
```

This way showdown.js should be forced to not convert the block in any way.

**Comment by westarne** [comment]
Regarding this problem a new syntax is introduced in the next version (1.7.2). (Updates for `vsc-elearnjs` and `atom-elearnjs` will follow)

You will then be able to deactivate the markdown conversion in a block. This might not be that useful for really short blocks, but for longer block formulas or texts containing no actual markdown.

### Normal Conversion

```markdown
This is a block in which no markdown should be processed.
It can contain $formulas__with$ anything $markdown *would__convert*$.
```

Converts to:

```html
<p>
This is a block in which no markdown should be processed.
It can contain $formulas<strong>with$ anything $markdown <em>would</strong>convert</em>$.
</p>
```

### Markdown Disabled Block

```markdown
<!--markdown-disable-->
This is a block in which no markdown should be processed.
It can contain $formulas__with$ anything $markdown *would__convert*$.
<!--markdown-enable-->
```

Converts to:

```html
This is a block in which no markdown should be processed.
It can contain $formulas__with$ anything $markdown *would__convert*$.
```

Please note the missing `<p>`. This might lead to unexpected results. If you want the additional `<p>` you can simply use the usual Showdown behavior, not converting Markdown inside of Html:

```markdown
<p>
This is a block in which no markdown should be processed.
It can contain $formulas__with$ anything $markdown *would__convert*$.
</p>
```
